### ISSUE TITLE
cascade_transition

### ISSUE THREAD

**Issue by chadyred** [sebdesign/laravel-state-machine#56]
Hello, is it possible to do cascade transition between 2 state machine ?

This an exemple from sylius which apply a transition between 2 state machine in order to move state from a state machine to another ( see `do: ["@sm.callback.cascade_transition", "apply"] `)

```
winzou_state_machine:
    sylius_shipment:
        class: "%sylius.model.shipment.class%"
        property_path: state
        graph: sylius_shipment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            ready: ~
            shipped: ~
            in_preparation: ~
            cancelled: ~
        transitions:
            create:
                from: [cart]
                to: ready
            prepare:
                from: [ready]
                to: in_preparation
            ship:
                from: [ready,in_preparation]
                to: shipped
            cancel:
                from: [ready, in_preparation]
                to: cancelled
        callbacks:
            after:
                sylius_prepare_order_shipping:
                    on: ["prepare"]
                    do: ["@sm.callback.cascade_transition", "apply"] # HERE WE CALL THE NEXT STATE MACHINE
                    args: ["object.getOrder()", "event", "'prepare'", "'sylius_order_shipping'"]

    sylius_order_shipping:
        class: "%sylius.model.order.class%"
        property_path: shippingState
        graph: sylius_order_shipping
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            ready: ~
            in_preparation: ~
            cancelled: ~
            partially_shipped: ~
            shipped: ~
        transitions:
            request_shipping:
                from: [cart]
                to: ready
            prepare:
                from: [ready]
                to: in_preparation
```
